### ISSUE TITLE
[feature request] add support for printing matches to constants 

### ISSUE THREAD

**Issue by finostro** [ros2/rosidl_runtime_py#28]
Hello, 
I have made a small modification to add support to print matches to constants that are defined in the msg:

 here is an example for a custom msg with ```uint8      MODE_SWITCH_AUTONOMOUS       = 1```
 in the .msg file

```
mode_switch: 1           (MODE_SWITCH_AUTONOMOUS)
fuel_tank: 65.0
```
I have made this patch on the humble branch, since i want to use it on humble. 
However if this sounds interesting I would like to replicate them on rolling.

**Comment by sloretz** [comment]
Thank you for the feature suggestion. I think the desire is to one day support this case with enum's in the message description format https://github.com/ros2/rosidl/issues/260 . I'll close this issue in favor of that one.

**Comment by finostro** [comment]
That sounds really good for the future . 
So my guess that means you would not consider this feature in pull request, since its better to wait for enums?
Thanks
